// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xilzawjovcgrzcixbozh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhpbHphd2pvdmNncnpjaXhib3poIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNjI4MTQsImV4cCI6MjA3MjkzODgxNH0.VVFu9xBt1aaoDV4UfE1vk_kQf39nwee6mx_TPsgUq4Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});